### ISSUE TITLE
大佬，如果有多个订阅链接怎么都添加进去呢

### ISSUE THREAD

**Issue by lichaoyangnice** [createkk/openclash_router_configs#1]

**Comment by createkk** [comment]
增加如下，需要更改的有subscribe_groups、hj_sub，这两个内容改一下名字

    subscribe_groups:
        type: http # http 的 path 可空置,默认储存路径为 homedir的proxies文件夹,文件名为url的md5
        url: "" #订阅链接存放在双引号内
        interval: 86400 #机场订阅自动更新时间 单位：秒
        path: ./hj_sub.yaml # 默认只允许存储在 clash 的 Home Dir，如果想存储到任意位置，添加环境变量 SKIP_SAFE_PATH_CHECK=1
        health-check:
            enable: true
            interval: 83214
            # lazy: true
            url: http://connectivitycheck.gstatic.com/generate_204

**Comment by createkk** [comment]
然后在上方这个地方增加
      use:
          - subscribe_groups 
          - 你的命名
