### ISSUE TITLE
大佬，配置文件已经用上了，按照视频设置的旁路由，youtube能登上，当播放不了，一直转圈，Google登不上

### ISSUE THREAD

**Issue by Kof-Q** [createkk/openclash_router_configs#3]

**Comment by Kof-Q** [comment]
2024-01-12 13:13:47 level=warning msg="[TCP] dial DIRECT (match RuleSet/icloud) 192.168.50.50:57738 --> setup.icloud.com:443 error: dns resolve failed: context deadline exceeded"

**Comment by createkk** [comment]
DNS相关配置贴一下

**Comment by Kof-Q** [comment]
![1705102879260](https://github.com/createkk/openclash_router_configs/assets/156150503/a35c0796-7a59-41c8-8973-ab7657625639)
![1705102896168](https://github.com/createkk/openclash_router_configs/assets/156150503/a4d53f8e-5d13-423d-bde6-04c1488f602a)
是这个吗？

**Comment by Kof-Q** [comment]
![image](https://github.com/createkk/openclash_router_configs/assets/156150503/fbd6b03b-7067-4a66-8cea-1aa875e4c880)
这里的分流选择了没有其作用

**Comment by Kof-Q** [comment]
> DNS相关配置贴一下

现在能上了，但clash面版那的分流设置里，无法按照我选择的节点进行分流，都是按
![image](https://github.com/createkk/openclash_router_configs/assets/156150503/a067dc48-d248-441d-9433-4158224a952c)
这个2个的组里的跑

**Comment by Kof-Q** [comment]
![image](https://github.com/createkk/openclash_router_configs/assets/156150503/d66c5797-c0c3-428e-a86b-e5cb7d9dcbbe)

**Comment by Kof-Q** [comment]
![image](https://github.com/createkk/openclash_router_configs/assets/156150503/8faa934e-daac-48a9-9cb4-591e3fed72be)

**Comment by createkk** [comment]
配置文件中的DNS写的是什么？

**Comment by Kof-Q** [comment]
> 配置文件中的DNS写的是什么？

![1705286669766](https://github.com/createkk/openclash_router_configs/assets/156150503/b8c08efc-8a73-4fd4-97ce-28e2746d218f)
都是按照你的视频讲解来一步步操作的

**Comment by createkk** [comment]
你这个内核是在哪里更新的，是这个地址吗？
https://github.com/vernesong/OpenClash/tree/core/dev/meta

**Comment by createkk** [comment]
底下还有个DNS的，你看看你主页的面板中是否选择了rule模式，是这个模式的话应该可以分流的

**Comment by Kof-Q** [comment]
> 你这个内核是在哪里更新的，是这个地址吗？ https://github.com/vernesong/OpenClash/tree/core/dev/meta

嗯，就是这里更新的，按你的操作更新了

**Comment by Kof-Q** [comment]
> 底下还有个DNS的，你看看你主页的面板中是否选择了rule模式，是这个模式的话应该可以分流的

![image](https://github.com/createkk/openclash_router_configs/assets/156150503/ec47c02b-9ab3-4dba-b27b-42f06f8d96bb)
![image](https://github.com/createkk/openclash_router_configs/assets/156150503/85dcbd9d-23de-4fd5-a181-971a98babc0c)

**Comment by createkk** [comment]
建议手动换一下内核测试
