### ISSUE TITLE
数据库订阅问题

### ISSUE THREAD

**Issue by vincent975** [createkk/openclash_router_configs#5]
请教哈，配置文件里有
geodata-mode: true
geox-url:                           # 自定义 geodata url, 需要有代理的前提才能下载geoip和geosite
    geoip: "https://gcore.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
    geosite: "https://gcore.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
    mmdb: "https://gcore.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"

哪openclash设置里的GEO 数据库订阅还需要打开吗？

**Comment by createkk** [comment]
不用
